// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuPj9kydMzXtUuHc3FIJNhAOoNYQV2Z0I',
    appId: '1:325974658415:web:24c001b1692a381197ac9a',
    messagingSenderId: '325974658415',
    projectId: 'franko-pizza',
    authDomain: 'franko-pizza.firebaseapp.com',
    storageBucket: 'franko-pizza.appspot.com',
    measurementId: 'G-QPFX8R5B94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5uK09HZED1EkqbCom9dIvyHTRaZ_gW9s',
    appId: '1:325974658415:android:5918b7ca9589f83a97ac9a',
    messagingSenderId: '325974658415',
    projectId: 'franko-pizza',
    storageBucket: 'franko-pizza.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe8eecEkSUhR9gq7kwyCnjWpzIXNgkKEs',
    appId: '1:325974658415:ios:f958611bcf9c64c997ac9a',
    messagingSenderId: '325974658415',
    projectId: 'franko-pizza',
    storageBucket: 'franko-pizza.appspot.com',
    iosBundleId: 'com.example.franko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe8eecEkSUhR9gq7kwyCnjWpzIXNgkKEs',
    appId: '1:325974658415:ios:0830d7b1d0a130fb97ac9a',
    messagingSenderId: '325974658415',
    projectId: 'franko-pizza',
    storageBucket: 'franko-pizza.appspot.com',
    iosBundleId: 'com.example.franko.RunnerTests',
  );
}
